config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers, :likes
    end
  end
  resources :posts do
    collection do
      post :confirm
    end
    resources :likes, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  mount LetterOpenerWeb::Engine, at: '/letter_opener'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_login_form.html.erb
<% provide(:button_text, '登録する') %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.text_field :name, class: 'form-control', placeholder: '名前' %>
  <%= f.email_field :email, class: 'form-control', placeholder: 'メールアドレス' %>
  <%= f.password_field :password, class: 'form-control', placeholder: 'パスワード' %>
  <%= f.password_field :password_confirmation, class: 'form-control', placeholder:'パスワード（再入力）' %>

  <%= f.submit yield(:button_text), class: "btn btn-lg btn-primary btn-block btn-signin" %>
<% end %>

app/views/shared/_post_form.html.erb
<h2 class="new-post-title"><%= yield :title %></h2>
<%= form_with(model: @post, local: true, url: choose_new_or_edit) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <span class="photo">
    <%= f.file_field :photo, id: :post_photo, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  <div class="field">
    <%= f.text_area :content, id: :post_content, placeholder: "コメントを入力" %>
  </div>
  <%= f.submit "送信", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('#post_photo').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('ファイルサイズは最大5MBです。');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <span>フォロー</span>

  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <span>フォロワー</span>
  </a>
  <a href="<%= likes_user_path(@user) %>">
    <strong id="likes" class="stat">
      <%= @user.likes.count %>
    </strong>
    <span>いいね</span>
  </a>
</div>

app/views/shared/_user_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.text_field :name, class: 'form-control', placeholder: '名前' %>
  <%= f.email_field :email, class: 'form-control', placeholder: 'メールアドレス' %>
  <%= f.password_field :password, class: 'form-control', placeholder: 'パスワード' %>
  <%= f.password_field :password_confirmation, class: 'form-control', placeholder:'パスワード（再入力）' %>
  <% unless action_name == 'home' %>
    <p>ユーザー画像</p>
    <%= image_tag @user.avatar.url if @user.avatar.present? %>
    <%= f.file_field :avatar, class: 'avatar' %>
  <% end %>

  <%= f.submit yield(:button_text), class: "btn btn-lg btn-primary btn-block btn-signin" %>
<% end %>

app/views/shared/_user_info.html.erb
<% if current_user.avatar.present? %>
  <%= image_tag current_user.avatar.thumb.url, alt: current_user.name, class: "avatar" %>
<% else %>
  <%= image_tag 'avatar_thumb.png', alt: current_user.name, class: "avatar" %>
<% end %>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィールを表示", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>