config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers, :likes
    end
  end
  resources :posts do
    collection do
      post :confirm
    end
    resources :likes, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  mount LetterOpenerWeb::Engine, at: '/letter_opener'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :like_users, through: :likes, source: :user
  default_scope -> { order(created_at: :desc)}
  mount_uploader :photo, PhotoUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :photo_size

  private

  def photo_size
    if photo.size > 5.megabytes
      errors.add(:photo, "should be less than 5MB")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :edit, :destroy]
  before_action :correct_user, only: [:edit, :destroy]

  def new
    if params[:back]
      @post = current_user.posts.build(post_params)
    else
      @post = current_user.posts.build
    end
  end

  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      PostMailer.post_mail(@post).deliver
      flash[:success] = "投稿しました！"
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'static_pages/home'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "編集しました"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "削除しました"
    redirect_to request.referrer || root_url
  end

  private

  def post_params
    params.require(:post).permit(:content, :photo, :photo_cache)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/views/posts/_like.html.erb
<% if post.likes.pluck(:user_id).include?(current_user.id) %> <!-- n+1回避 -->
  <!-- ここから要リファクタリング -->
  <% like_id = post.likes.find_by(user_id: current_user.id).id %>
  <%= button_to post_like_path(id: like_id, post_id: post.id), method: :delete,
                              id: "like-button", class: "like-button", remote: true do %>
    <%= image_tag("heart_on.svg", width: 20, height: 20) %>
    <span><%= post.likes_count %></span>
  <% end %>
  <!-- ここまで要リファクタリング -->
<% else %>
  <%= button_to post_likes_path(post_id: post.id), method: :post, id: "like-button",
                              class: "like-button", remote: true do %>
    <%= image_tag("heart_off.svg", width: 20, height: 20) %>
    <span><%= post.likes_count %></span>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <div class="post-header">
    <% if post.user.avatar.present? %>
      <%= image_tag post.user.avatar.thumb.url ,alt: post.user.name, class: "avatar" %>
    <% else %>
      <%= image_tag 'avatar_thumb.png', alt: post.user.name, class: "avatar" %>
    <% end %>
    <span class="user"><%= link_to post.user.name, post.user %></span>
  </div>
  <div class="content-photo">
    <%= image_tag post.photo.url if post.photo? %>
  </div>
  <% if post.user != current_user %>
    <div id="content-like-<%= post.id %>">
      <%= render 'posts/like', post: post %>
    </div>
  <% end %>
  <div class="content-text">
    <%= post.content %>
  </div>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    <% if current_user?(post.user) %>
      <%= link_to "編集", edit_post_path(post) %> |
      <%= link_to "削除", post, method: :delete,
                    data: { confirm: "削除してよろしいですか？" } %>
    <% end %>
  </span>
</li>

app/views/posts/confirm.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2 class="new-post-title">以下の内容で送信します。</h2>
    <%= form_with(model: @post, url: posts_path, local: true) do |f| %>
      <%= f.hidden_field :photo_cache %>
      <%= f.hidden_field :content %>

      <div class="confirm-content-photo">
        <%= image_tag @post.photo %>
      </div>
      <h3>Comment</h3>
      <div class="confirm-content-text">
        <%= @post.content %>
      </div>
      <%= f.submit "投稿する", class: "btn btn-primary" %>
    <% end %>

    <%= form_with(model: @post, url: new_post_path, local: true, method: "get") do |f| %>
      <%= f.hidden_field :photo_cache %>
      <%= f.hidden_field :content %>
      <%= f.submit "戻る", name: 'back', class: "btn" %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<% provide(:title, "編集する") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/post_form' %>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "写真を投稿する") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/post_form' %>
  </div>
</div>